//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourceful.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int ScheduleDetailID { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> ScheduleStartTime { get; set; }
        public Nullable<System.DateTime> ScheduleEndTime { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
