//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourceful.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int ScheduleID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
